### ISSUE TITLE
Hey, I'm Having a render screen error

### ISSUE THREAD

**Issue by JorgeFly1109** [Krengus/DU_ASTco#4]

**Comment by smooreace** [comment]
Your video card cant handle the game

**Comment by JorgeFly1109** [comment]
> Your video card cant handle the game

Lol, I have a Nidia 4080, there is a script error when you activate the PB. Somthing deprecated...

**Comment by JorgeFly1109** [comment]
![Screenshot_1363](https://user-images.githubusercontent.com/82549045/205108652-607fff61-e6a7-4c92-b50e-9fd15be0ceac.png)
There is a screenshot

**Comment by smooreace** [comment]
You posted an "Issue" with a worthless title and gave zero intelligent supporting information.... so you got an equally worthless response. See how that works!

Now that you LOOKED at what the error says you can see what the problem is, and considering that there has been no communication from the guy the wrote the script for months and the update that deprecated library. start was released almost 4 months ago, Ide be looking elsewhere. I'de suggest the following

https://github.com/Jericho1060/du-container-monitoring

https://github.com/Jericho1060/du-storage-monitoring

Both are excellent, and from a very active player in a top 10 Org

**Comment by Krengus** [comment]
Having fun here ? :)

This seems to be about honeycombsControl script, you're linking alternative for storage scripts.
Honeycomb scripts is indeed still using deprecated stuff, anyone is free to take over, i havent found any alternative yet, or worked on a fix indeed. Yet it's still fully functionnal

**Comment by JorgeFly1109** [comment]
Those scripts don't manage a honeycombe factory, nothing to do with this script.

**Comment by JorgeFly1109** [comment]
> You posted an "Issue" with a worthless title and gave zero intelligent supporting information.... so you got an equally worthless response. See how that works!
> 
> Now that you LOOKED at what the error says you can see what the problem is, and considering that there has been no communication from the guy the wrote the script for months and the update that deprecated library. start was released almost 4 months ago, Ide be looking elsewhere. I'de suggest the following
> 
> https://github.com/Jericho1060/du-container-monitoring
> 
> https://github.com/Jericho1060/du-storage-monitoring
> 
> Both are excellent, and from a very active player in a top 10 Org

Srry to bother you, IT pro  guru of the space. Fly Safe, U r really an AH

**Comment by JorgeFly1109** [comment]
> Having fun here ? :)
> 
> This seems to be about honeycombsControl script, you're linking alternative for storage scripts. Honeycomb scripts is indeed still using deprecated stuff, anyone is free to take over, i havent found any alternative yet, or worked on a fix indeed. Yet it's still fully functionnal

Hey Krengu thx for your reply! Ill wait then if someone knows how to fix it. THX!
